name: Platformio
on: [workflow_dispatch, push]

jobs:
  build:
    strategy:
        fail-fast: true
        matrix: 
          targets: [esp32-bwr, esp32-bw]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./firmware/esp32_2-9in
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Check file existence
      id: check_files
      uses: andstor/file-existence-action@v2
      with:
          files: "data"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install PlatformIO
      run: pip install --upgrade platformio

    - name: Compile Firmware
      run: pio run -e ${{ matrix.targets }}
    - name: Rename Firmware
      run: mv .pio/build/${{ matrix.targets }}/firmware.bin ${{ matrix.targets }}-firmware.bin
    - name: Upload Firmware
      uses: actions/upload-artifact@v3
      with: 
        name: firmware
        path: ./firmware/esp32_2-9in/${{ matrix.targets }}-firmware.bin


  release:

    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Download Firmware Files
      uses: actions/download-artifact@v3
      with:
        path: ./releases

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ./releases

    - name: Release Firmware
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./releases/firmware/*-firmware.bin
        generateReleaseNotes: true
        allowUpdates: true